### ISSUE TITLE
Drag & Drop: Strange behavior

### ISSUE THREAD

**Issue by SPQRInc** [pagekit/pagekit#874]
## Problem

Hello,

I am using  Pagekit 1.0.13. Creating a site tree with a lot of elements causes some strange behavior:

## Auto-selection of child nodes

Auto-selection of child-nodes is a bit confusing as you see in this screencast.

![2017-10-20 09 40 04](https://user-images.githubusercontent.com/23051150/31811567-45df1b82-b580-11e7-9e87-8c306f5b34ee.gif)

Selecting the second element causes the root element ("Blog") to be selected. 

Please also have a look at the behavior in this case:

![2017-10-20 09 43 47](https://user-images.githubusercontent.com/23051150/31811631-88d709c2-b580-11e7-9a69-0a762ae24c7e.gif)

## Duplication

Another problem: Moving items on larger site-trees sometimes leads to duplication (I need to reload the page to solve this)

![2017-10-20 10 16 17](https://user-images.githubusercontent.com/23051150/31811692-bcf3f666-b580-11e7-8a88-d5e9c0e47f3c.gif)

## It's not comfortable to move elements

If you are working on larger site-trees on small devices is not really comfortable, too:

![2017-10-20 10 17 03](https://user-images.githubusercontent.com/23051150/31811717-d7e6052c-b580-11e7-9b84-1c926b67d4f8.gif)

Maybe this can be improved? E.g. Joomla! let's you define the root-element in the child's details page. 

## Problems with some browsers

As a user told me on https://pagekit-forum.org/forum/thread/186-drag-drop-sites/?postID=890#post890, there are also problems with different browsers. Using Edge solved this.

Maybe you could have a look at this and provide a little bugfix, that makes working with drag & drop more comfortable?

## Problems on mobile devices

Also, if you are working on mobile, you drag & drop your menu structure, even if you don't want to (I tried to scroll, but I moved the site tree elements).

### Summary

- Strange behavior when I click elements that have child-elements
- Duplication when I move elements
- It's not comfortable to move elements with a lot of child elements
- Moving the elements does not work on some browsers at all
- Moving the elements on mobile devices can be done accidentally 
 
## Technical Details

- Pagekit version: 1.0.13
- Webserver: Apache 2.4
- Database: SQLite
- PHP Version: PHP 7.1.2

**Comment by violoncelloch** [comment]
the "Problems with some browesers" issue seems to be a problem with devices with a touchscreen and mouse... Actual versions of Chrome and Firefox 57< are affected but Edge still works

**Comment by helmutkaufmann** [comment]
I just tried Edge on an iPad. It does not work (anymore) either.

**Comment by violoncelloch** [comment]
I think we have to wait for pagekit to upgrade to uikit 3... The issue is solved in uikit 3... According to yootheme this upgrade will come later this year...

**Comment by NoodleBB** [comment]
This bug still exists. - Is PageKit under active developement?
