### ISSUE TITLE
Edit Widget Tab Automatic Toggle On Select Text

### ISSUE THREAD

**Issue by yorkadam** [pagekit/pagekit#897]
## Problem
In widget edit mode attempting to select text with the right mouse button from left or right causes the tabs to switch to theme when the cursor highlight has reached the end of the text or moved outside of the edit box making it hard to select text for cut, copy, paste.

## Technical Details

Steps to reproduce
1. Create a new text widget
2. Enter text into the title input box
3. Enter single line of text into the main text box (text only no MD or HTML)
4. Position anywhere on the site
5. Save
6. Go back to edit the widget
7. Attempt to highlight the text in the main text box using the right mouse button.
8. Drag the highlighter (mouse cursor) to the end of text and release  right mouse button
9. Result: Tab switches to Theme tab
10. Expected Result: Highlight of text without switching to a different tab.

To clarify, switching to tab occurs on the **_mouse-up event_** when releasing the button at the end of text selection.  This happens frequently on Firefox making it hard to use FF. But happens much less on Vivaldi.

Debug mode does not seem to report any errors

The JavaScript Console does not report any errors but does report the following warnings:
Note: URL with ...... is just a place holder and not the actual path where ..... represents the base install path where pagekit zip was extracted without modification to:  /var/www/html/pagekit

Warnings:
Source map error: request failed with status 404
Resource URL: ......./app/assets/jquery/dist/jquery.min.js?v=8e82
Source Map URL: jquery.min.map
Source map error: request failed with status 404
Resource URL: ....../app/assets/vue/dist/vue.min.js?v=8e82
Source Map URL: vue.min.js.map

- Pagekit version: 1.0.13
- Webserver: Apache/2.4.18 (Ubuntu)
- Database: sqlite
- PHP Version: 7.0.28-0ubuntu0.16.04.1
- Browser: FireFox 59.0.2
- Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
- Browser  Vivaldi  1.14.1077.60 (Stable channel) (64-bit)
- User Agents: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) -
- User Agents: Chrome/64.0.3282.189 Safari/537.36 Vivaldi/1.95.1077.60
- Built On: Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64
- Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Comment by erikperin** [comment]
I have the same problem

**Comment by stankiewiczpl** [comment]
I fixed it here :
app/system/modules/widget/app/views/edit.js 
var tab = UIkit.tab(this.$els.tab, {connect: this.$els.content});
to
var tab = UIkit.tab(this.$els.tab, {swiping:false, connect: this.$els.content});
and run webpack

**Comment by yorkadam** [comment]
I've been busy. Sorry it took so long go get back to this.  This appears to be working now. So, please close this issue. Or if you prefer I can close it.

**Comment by MonsieurPaulLeBoulanger** [comment]
For me the issue is still here : 

If I select the word (ie. Home) with my mouse while editing my page, the tab is automatically switched when I release the left button.

There are 2 behaviours : 
* if I select from right to left, I will be sent to the Theme tab
* if I select from left to right I will be sent to the Meta tab

pagekit v1.0.14
firefox 61
ubuntu 16.04
pagekit runs on a debian 9.4 server with apache 2.4.25 and php 7.0

**Comment by Ablu** [comment]
Same issue. This is very annoying when simply selecting text with a touchpad. Reproducible by simply having a longer line and selecting it by dragging left or right.

**Comment by yorkadam** [comment]
I ran the "Update" from inside of pagekit which updated it to 1.0.14 and the selection problem is back. So, not quite fixed yet.

**Comment by humantex** [comment]
@stankiewiczpl ...

After updating pagekit to 1.0.15, I tried to modify the minified version of edit.js ( /app/system/modules/widget/app/bundle/edit.js ), as I can't run webpack in a shared hosting environment. Since I don't edit any pagekit sites on a phone or tablet I can't confirm that this would solve the problem, but it seems this isn't a fix for using a mouse in a desktop browser for mouse-up/mouse-down actions.

The only workaround is to use shift + tab/arrow keys to do the selections, and that's unacceptable when inserting mountains of copy/paste content being transplanted from another CMS.

Is there an alternative to adding the 'swipe' setting that would cover ALL editing instances for every device type?

**Comment by humantex** [comment]
Although I'm sure I had updated to 1.0.15 before re-editing 'edit.js', I came back several weeks later to find an update notification for 1.0.15 on the admin dashboard... (???)

After another update and editing a freshly unminified version - I found the section noted by @stankiewiczpl had changed somewhat, and now uses 'this', as `var t = this;` instead of the `var tab = UIkit.tab(...;` from its previous version.

The insertion of `swiping:false,` seems to have tamed the tab switching behavior on desktop browsers. The complete block of code (lines 39 to 48) in my unminified version ( /app/system/modules/site/app/bundle/edit.js ) now reads:

```
            ready: function () {
                var t = this;
                this.Nodes = this.$resource("api/site/node{/id}"), this.tab = UIkit.tab(this.$els.tab, {
                    swiping:false, connect: this.$els.content
                }), this.tab.on("change.uk.tab", function (e, o) {
                    t.active = o.index()
                }), this.$watch("active", function (t) {
                    this.tab.switcher.show(t)
                }), this.$state("active")
            },
```

As noted earlier, I don't edit Pagekit sites on mobile devices with swipe functionality, so I'm unsure how this might affect admins/editors that do use them.

**Comment by ChrisCullen** [comment]
@humantex
I edited the bundle file "app\system\modules\widget\app\bundle\edit.js" as well with **stankiewiczpl**'s fix and it fixed it for me on a shared host.

**Comment by TopsysLastCigarette** [comment]
Hi, 
I think this is probably an UIKit relevant issue. Problem solved in UIKit 3 release.
Of course, Pagekit runs with UIKit2 and we have to wait for an update. 

I found a little solution which works for me currently,  it consists of changing the swiping value of tab directly in the uikit.min.js :

-  In your pagekit folder, **open** _`app\assets\uikit\js\uikit.min.js`_ 

- **Find** this piece of line `function(t){"use strict";t.component("tab",{defaults:{target:">li:not(.uk-tab-responsive, .uk-disabled)",connect:!1,active:0,animation:!1,duration:200,swiping:!0}` 

(There is also a "switcher" component with a swiping variable which looks similar to that line but don't mix up !)

- **Change** the swiping value : `swiping:!0` to `swiping:!1` and save

- Refresh your dashboard

Hope this helps !

**Comment by corine138** [comment]
Have the same problem in many of my pagekit sites. Tried the solution posted by TopsysLastCigarette and this worked.
Would be nice if this would be fixed !

**Comment by buggalicious** [comment]
Feb 21, 2019, and still the same problem. For someone new to Pagekit, this is almost a deal breaker, when already the most basis element, the editor, doesn't work properly.

**Comment by jiri-novacek** [comment]
I can confirm, as "someone new to Pagekit", jumping through various CMS to find the one ideal for me, this is a deal breaker. It took like whole 5 seconds after installation to experience this nonsense behavior while selecting text in editor.
And I can also confirm that solution provided by anthonysaurina (editing uikit.min.js) worked well.
